config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"

  resources :players, only: [:index, :show] do
    resources :favorites, only: [:create]
  end



  resources :team_players, only: [:destroy]

  resources :teams, only: [:index, :show, :new, :create] do
    resources :team_players, only: [:new, :create]
    resources :matches, only: :create
    get "favorites-add", to: "favorites#add"
    get "favorites-rem", to: "favorites#remove"
  end

  get "favorites", to: "favorites#index"

  resources :matches, only: [:index, :show]

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :match
  has_many :messages
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_player, class_name: "User"
  belongs_to :away_player, class_name: "User"
  has_many :chatrooms
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/player.rb
class Player < ApplicationRecord
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_role_and_name_and_club_and_nationality,
    against: [ :name, :role, :club, :nationality ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :team_players

  validates :name, presence: true
  validates :name, uniqueness: true

  acts_as_favoritable
end

app/models/team_player.rb
class TeamPlayer < ApplicationRecord
  belongs_to :player
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :teams
  has_many :matches_as_away_player, class_name: "Match", foreign_key: :home_player_id
  has_many :matches_as_home_player, class_name: "Match", foreign_key: :away_player_id

  acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def index;end

  def add
    team = Team.find(params[:team_id])
    current_user.favorite(team)
    redirect_to team_path(team)
  end

  def remove
    team = Team.find(params[:team_id])
    current_user.unfavorite(team)
    redirect_to team_path(team)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    raise
    @matches = []
    if user_signed_in?
      @matches = current_user.matches_as_home_player
      @matches.concat(current_user.matches_as_away_player)
    end
  end
  def show
    @match = Match.find(params[:id])
  end

  def create
    @user = Team.find(params[:team_id]).user
    @match = Match.new(home_player: @user, away_player: current_user)
    Chatroom.create!(match: @match)

    if @match.save
      redirect_to match_path(@match)
    else
      render 'teams/show', status: :unprocessable_entity
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user

    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render 'chatrooms/show', status: :unprocessable_entity
    end

  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @favorite = Favorite.new

    if params[:query].present?
      @players = Player.search_by_role_and_name_and_club_and_nationality(params[:query])
    else
      @players = Player.all
    end
  end

  def show
  end
end

app/controllers/team_players_controller.rb
class TeamPlayersController < ApplicationController

  def create
    @player = Player.find(params[:team_player][:player_id])
    @team = Team.find(params[:team_id])
    @team_player = TeamPlayer.new
    @team_player.player = @player
    @team_player.team = @team

    if @team_player.save
      redirect_to team_path(@team)
    else
      render 'teams/show', status: :unprocessable_entity
    end
  end

  def destroy
    @team_player = TeamPlayer.find(params[:id])
    @team_player.destroy
    redirect_to team_path(@team_player.team), status: :see_other
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def show
    @team = Team.find(params[:id])
    @team_player = TeamPlayer.new
    @match = Match.new
  end

  def create
    @team = Team.new(team_params)
    @team.user = current_user

    if @team.save
      redirect_to team_path(@team)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<div class="container chatroom"
     data-controller="chatroom-subscription"
     data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">

  <h1>#<%= @chatroom.match.home_player.teams.last.name %> vs <%= @chatroom.match.away_player.teams.last.name %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>

  <%= simple_form_for [@chatroom, @message],
    html: {
      data: { action: "turbo:submit-end->chatroom-subscription#resetForm" },
      class: "d-flex"
    } do |f| %>

    <%= f.input :content,
      label: false,
      placeholder: "Message",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>

</div>

app/views/favorites/index.html.erb
<h1>My Favorites Teams</h1>
<ul>
  <% current_user.all_favorites.each do |fav| %>
    <li><p><%= link_to fav.favoritable.name, team_path(fav.favoritable) %></p></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fm2022</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/matches/index.html.erb
<h1>Matches</h1>
<ul>
  <% @matches.each do |match| %>
     <% text = " #{match.home_player.teams.last.name} VS #{match.away_player.teams.last.name}" %>
    <li>
      <%= link_to text,  match_path(match) %>
    </li>
  <% end %>
</ul>

app/views/matches/show.html.erb
<h1><%= @match.home_player.teams.last.name %> vs <%= @match.away_player.teams.last.name %></h1>
<%= link_to 'Messages', chatroom_path(@match.chatrooms.last) %>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.name %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<h1>Football Manager 2022</h1>

<div class="container">
  <%= image_tag "https://cdn.footballmanager.com/site/2021-09/FM22%20Opengraph_0.jpg"%>
</div>

app/views/players/index.html.erb
<h1>Players#index</h1>
<div class="container">
  <%= form_with url: players_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a player"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

  <br>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-8">
        <div id="movies">
          <% @players.each do |player| %>
            <h4><%= player.name%></h4>
            <p><%= player.club %></p>
            <p><%= player.nationality %></p>
            <p><%= player.id %></p>
            <button data-action="click->favorite#send"
                    data-controller="favorite"
                    data-favorite-id-value="<%= player.id%>">
              <i class="fab fa-gratipay fa-2x" id='favorite-link'></i>
            </button>

          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/players/show.html.erb
<h1>Players#show</h1>
<p>Find me in app/views/players/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "Teams", teams_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "Players", players_path, class: "nav-link" %>
          </li>

          <%if current_user.teams.blank? %>
            <li class="nav-item">
              <%= link_to "New Team", new_team_path, class: "nav-link" %>
            </li>
          <% else %>
            <%= link_to current_user.teams.last.name, team_path(current_user.teams.last), class: "nav-link" %>
          <% end %>

          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Matches", matches_path, class: "dropdown-item" %>
              <%= link_to "Favorites Teams", favorites_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>